apiVersion: v1
kind: Service
metadata:
  name: analytics-api
  namespace: go-k8s-analytics
spec:
  selector:
    app.kubernetes.io/instance: analytics-api
  ports:
  - port: 3000
    targetPort: 3000
