apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  namespace: go-k8s-analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: analytics-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 ## Ensure that we do not have more than 3 pod replicas running at any given time
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics-api
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: analytics-api
    spec:
      restartPolicy: Always
      containers:
      - name: analytics-api
        image: dunky2012/analytics-api:0.0.1-release
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
        envFrom:
          - configMapRef:
              name: app-cm
        ports:
          - containerPort: 3000

