apiVersion: v1
kind: Pod
metadata:
  name: analytics-api
  namespace: go-k8s-analytics
  labels:
    app.kubernetes.io/name: analytics-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: analytics-api
spec:
  containers:
  - name: analytics-api
    image: dunky2012/analytics-api:0.0.1-release
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
    envFrom:
      - configMapRef:
          name: app-cm
    ports:
      - containerPort: 3000
