version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    networks:
      - springbankNet
    env_file:
      - .env  # Load environment variables securely
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      #- ~/pgdata/largedb:/mnt/largedb # Only use this if frequently importing/exporting large datasets

networks:
  springbankNet:
    external: true
    driver: bridge

volumes:
  pg_data:
