apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: go-k8s-analytics
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  hostPath:
    path: /var/lib/postgresql/data

